from django.conf.urls import url

import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.loginpage,  name="loginpage"),
    url(r'^loginrequest$', views.loginrequest, name='loginrequest'),
    url(r'^logout$', views.logout_view,  name="hal-logout"),

    url(r'^perusahaan$', views.dashboard.perusahaan_index,  name="perusahaan-index"),
    url(r'^departemen$', views.dashboard.departemen_index,  name="departemen-index"),
    #url(r'^unit$', views.dashboard.unit_index, name="unit-index"),
  	url(r'^bagian$', views.dashboard.bagian_index, name="bagian-index"),
  	url(r'^golongan$', views.dashboard.golongan_index, name="golongan-index"),
  	url(r'^jabatan$', views.dashboard.jabatan_index, name="jabatan-index"),
  	url(r'^bank$', views.dashboard.bank_index, name="bank-index"),
  	url(r'^agama$', views.dashboard.agama_index, name="agama-index"),
  	url(r'^warganegara$', views.dashboard.warganegara_index, name="warganegara-index"),
  	url(r'^statusmenikah$', views.dashboard.statusmenikah_index, name="statusmenikah-index"),
    url(r'^profile-perusahaan$', views.dashboard.profile_perusahaan_index, name="profile-perusahaan-index"),
    url(r'^karyawan$', views.dashboard.karyawan_index, name="karyawan-index"),
    url(r'^karyawan/(?P<karyawan_id>[0-9]+)/detail/$', views.dashboard.karyawan_detail, name="karyawan-detail"),
    url(r'^karyawan-shift$', views.dashboard.karyawan_shift_index, name="karyawan-shift-index"),
    url(r'^shift$', views.dashboard.shift_index, name="shift-index"),
    url(r'^hariraya$', views.dashboard.hariraya_index, name="hariraya-index"),
    url(r'^absensi$', views.dashboard.absensi_index, name="absensi-index"),
    url(r'^inventory$', views.dashboard.inventory_index, name="inventory-index"),
    url(r'^konfigurasi$', views.dashboard.konfigurasi_index, name="konfigurasi-index"),
    url(r'^mesin$', views.dashboard.mesin_index, name="mesin-index"),
    url(r'^overtime$', views.dashboard.overtime_index, name="overtime-index"),
    url(r'^postinggaji$', views.dashboard.postinggaji_index, name="postinggaji-index"),
    url(r'^potongankaryawan$', views.dashboard.potongankaryawan_index, name="potongankaryawan-index"),
    url(r'^pinjaman$', views.dashboard.pinjaman_index, name="pinjaman-index"),
    url(r'^masatenggangclosing$', views.dashboard.masatenggangclosing_index, name="masatenggangclosing-index"),
    url(r'^izincuti$', views.dashboard.izincuti_index, name="izincuti-index"),
    url(r'^laporan/gaji$', views.dashboard.laporangaji_index, name="laporangaji-index"),    
    url(r'^laporan/absensi$', views.dashboard.laporanabsensi_index, name="laporanabsensi-index"),
    url(r'^laporan/pinjaman/karyawan$', views.dashboard.laporanpinjamankaryawan_index, name="laporanpinjamankaryawan-index"),
    url(r'^laporan/datakaryawan$', views.dashboard.datakaryawan_index, name="datakaryawan-index"),
    url(r'^laporan/bpjs$', views.dashboard.laporanbpjs_index, name="laporanbpjs-index"),
    url(r'^tunjangankaryawan$', views.dashboard.tunjangankaryawan_index, name="tunjangankaryawan-index"),    
    url(r'^bonusthr$', views.dashboard.bonusthr_index, name="bonusthr-index"),    
    url(r'^bpjs$', views.dashboard.bpjs_index, name="bpjs-index"),
    url(r'^ptkp$', views.dashboard.ptkp_index, name="ptkp-index"),
    # url(r'^gaji$', views.dashboard.gaji_index, name="gaji-index"),
  	#url(r'^notif-system$', views.dashboard.notif_system, name="notif-system-index"),
  	#url(r'^notif-login$', views.dashboard.notif_login, name="notif-login-index"),
  	#url(r'^notif-aplikasi$', views.dashboard.notif_aplikasi, name="notif-aplikasi-index"),
  	#url(r'^notif-karyawan$', views.dashboard.notif_karyawan, name="notif-karyawans-index"),
  	#url(r'^notif-system$', views.dashboard.notif_system, name="notif-system-index"),

  	#url(r'^perusahaan$', views.dashboard.perusahaan_index,  name="perusahaan-index"),

    #==search
    url(r'^karyawan/search$', views.search.karyawan,  name="karyawan-search"),
    #==eof

    #==create

    url(r'^departemen/create$', views.create.departemen,  name="departemen-create"),
    url(r'^departemen/create/save$', views.create.departemen_save,  name="departemen-create-save"),
    url(r'^perusahaan/create$', views.create.perusahaan,  name="perusahaan-create"),
    url(r'^perusahaan/create/save$', views.create.perusahaan_save,  name="perusahaan-create-save"),
    url(r'^bagian/create$', views.create.bagian,  name="bagian-create"),
    url(r'^bagian/create/save$', views.create.bagian_save,  name="bagian-create-save"),
  	url(r'^golongan/create$', views.create.golongan, name="golongan-create"),
  	url(r'^golongan/create/save$', views.create.golongan_save, name="golongan-create-save"),
  	url(r'^jabatan/create$', views.create.jabatan, name="jabatan-create"),
  	url(r'^jabatan/create/save$', views.create.jabatan_save, name="jabatan-create-save"),
  	url(r'^bank/create$', views.create.bank, name="bank-create"),
  	url(r'^bank/create/save$', views.create.bank_save, name="bank-create-save"),
    url(r'^karyawan-shift/save$', views.create.karyawan_shift_save, name="karyawan-shift-create-save"),
    url(r'^shift/create$', views.create.shift, name="shift-create"),
    url(r'^shift/create/save$', views.create.shift_save, name="shift-create-save"),
    url(r'^hariraya/create$', views.create.hariraya, name="hariraya-create"),
    url(r'^hariraya/create/save$', views.create.hariraya_save, name="hariraya-create-save"),

  	url(r'^agama/create$', views.create.agama, name="agama-create"),
  	url(r'^agama/create/save$', views.create.agama_save, name="agama-create-save"),
  	url(r'^warganegara/create$', views.create.warganegara, name="warganegara-create"),
  	url(r'^warganegara/create/save$', views.create.warganegara_save, name="warganegara-create-save"),
    url(r'^statusmenikah/create$', views.create.statusmenikah, name="statusmenikah-create"),
    url(r'^statusmenikah/create/save$', views.create.statusmenikah_save, name="statusmenikah-create-save"),
    url(r'^profile-perusahaan/create$', views.create.profile_perusahaan, name="profile-perusahaan-create"),
    url(r'^profile-perusahaan/create/save$', views.create.profile_perusahaan_save, name="profile-perusahaan-create-save"),
    url(r'^karyawan/create$', views.create.karyawan, name="karyawan-create"),
    url(r'^karyawan/create/save$', views.create.karyawan_save, name="karyawan-create-save"),
    url(r'^inventory/create$', views.create.inventory, name="inventory-create"),
    url(r'^inventory/create/save$', views.create.inventory_save, name="inventory-create-save"),
    url(r'^konfigurasi/create$', views.create.konfigurasi, name="konfigurasi-create"),
    url(r'^konfigurasi/create/save$', views.create.konfigurasi_save, name="konfigurasi-create-save"),
    url(r'^pinjaman/create$', views.create.pinjaman, name="pinjaman-create"),
    url(r'^pinjaman/create/save$', views.create.pinjaman_save, name="pinjaman-create-save"),

    url(r'^absen/(?P<absensi_id>[0-9]+)/overtime/create$', views.create.overtime, name="overtime-create"),
    url(r'^download/(?P<dire>.*):(?P<path>.*)$', views.dashboard.download, name="download"),
    url(r'^absen/(?P<absensi_id>[0-9]+)/overtime/create/save$', views.create.karyawan_lembur_save, name="overtime-create-save"),
    url(r'^absen/(?P<absensi_id>[0-9]+)/koreksi/create$', views.create.koreksi, name="koreksi-create"),
    url(r'^absen/(?P<absensi_id>[0-9]+)/koreksi/create/save$', views.create.koreksi_save, name="koreksi-create-save"),
    url(r'^masatenggangclosing/create$', views.create.masatenggangclosing, name="masatenggangclosing-create"),
    url(r'^masatenggangclosing/create/save$', views.create.masatenggangclosing_save, name="masatenggangclosing-create-save"),
    url(r'^mesin/create$', views.create.mesin, name="mesin-create"),
    url(r'^mesin/create/save$', views.create.mesin_save, name="mesin-create-save"),

    # url(r'^gaji/create$', views.create.gaji, name="gaji-create"),
    # url(r'^gaji/create/save$', views.create.gaji_save, name="gaji-create-save"),
    url(r'^postinggaji/do/(?P<id>[0-9]+)$', views.posting.postinggaji, name="postinggaji-do"),
    url(r'^laporan/gaji/do$', views.laporan.laporangaji, name="laporangaji-do"),
    url(r'^laporan/datakaryawan/do$', views.datakaryawan.awal, name="datakaryawan-do"),
    url(r'^laporan/absensi/do$', views.laporan.laporanabsensi, name="laporanabsensi-do"),
    url(r'^laporan/bpjs/do$', views.laporan.laporanbpjs, name="laporanbpjs-do"),
    url(r'^laporan/pinjaman/do$', views.laporan.laporanpinjaman, name="laporanpinjaman-do"),


    #==eof-create
    #==edit

  	url(r'^departemen/(?P<departemen_id>[0-9]+)/edit/$', views.edit.departemen, name="departemen-edit"),
  	url(r'^departemen/(?P<departemen_id>[0-9]+)/edit/save$', views.edit.departemen_save, name="departemen-edit-save"),
    url(r'^perusahaan/(?P<perusahaan_id>[0-9]+)/edit/$', views.edit.perusahaan, name="perusahaan-edit"),
    url(r'^perusahaan/(?P<perusahaan_id>[0-9]+)/edit/save$', views.edit.perusahaan_save, name="perusahaan-edit-save"),
  	url(r'^bagian/(?P<bagian_id>[0-9]+)/edit/$', views.edit.bagian, name="bagian-edit"),
  	url(r'^bagian/(?P<bagian_id>[0-9]+)/edit/save$', views.edit.bagian_save, name="bagian-edit-save"),
  	url(r'^golongan/(?P<golongan_id>[0-9]+)/edit/$', views.edit.golongan, name="golongan-edit"),
  	url(r'^golongan/(?P<golongan_id>[0-9]+)/edit/save$', views.edit.golongan_save, name="golongan-edit-save"),
  	url(r'^jabatan/(?P<jabatan_id>[0-9]+)/edit/$', views.edit.jabatan, name="jabatan-edit"),
  	url(r'^jabatan/(?P<jabatan_id>[0-9]+)/edit/save$', views.edit.jabatan_save, name="jabatan-edit-save"),
  	url(r'^bank/(?P<bank_id>[0-9]+)/edit/$', views.edit.bank, name="bank-edit"),
  	url(r'^bank/(?P<bank_id>[0-9]+)/edit/save$', views.edit.bank_save, name="bank-edit-save"),

  	url(r'^agama/(?P<agama_id>[0-9]+)/edit/$', views.edit.agama, name="agama-edit"),
  	url(r'^agama/(?P<agama_id>[0-9]+)/edit/save$', views.edit.agama_save, name="agama-edit-save"),
  	url(r'^warganegara/(?P<warganegara_id>[0-9]+)/edit/$', views.edit.warganegara, name="warganegara-edit"),
  	url(r'^warganegara/(?P<warganegara_id>[0-9]+)/edit/save$', views.edit.warganegara_save, name="warganegara-edit-save"),
    url(r'^statusmenikah/(?P<statusmenikah_id>[0-9]+)/edit/$', views.edit.statusmenikah, name="statusmenikah-edit"),
    url(r'^statusmenikah/(?P<statusmenikah_id>[0-9]+)/edit/save$', views.edit.statusmenikah_save, name="statusmenikah-edit-save"),
    url(r'^profile-perusahaan/(?P<lokasiperusahaan_id>[0-9]+)/edit/$', views.edit.profile_perusahaan, name="profile-perusahaan-edit"),
    url(r'^profile-perusahaan/(?P<lokasiperusahaan_id>[0-9]+)/edit/save$', views.edit.profile_perusahaan_save, name="profile-perusahaan-edit-save"),
    url(r'^profile-perusahaan/profile-edit/$', views.edit.profile_edit, name="profile-edit"),
    url(r'^profile-perusahaan/profile-edit/edit/save$', views.edit.profile_edit_save, name="profile-edit-save"),
    url(r'^shift/(?P<shift_id>[0-9]+)/edit/$', views.edit.shift, name="shift-edit"),
    url(r'^shift/(?P<shift_id>[0-9]+)/edit/save$', views.edit.shift_save, name="shift-edit-save"),

    url(r'^hariraya/(?P<hariraya_id>[0-9]+)/edit/$', views.edit.hariraya, name="hariraya-edit"),
    url(r'^hariraya/(?P<hariraya_id>[0-9]+)/edit/save$', views.edit.hariraya_save, name="hariraya-edit-save"),
    url(r'^inventory/(?P<inventory_id>[0-9]+)/edit/$', views.edit.inventory, name="inventory-edit"),
    url(r'^inventory/(?P<inventory_id>[0-9]+)/edit/save$', views.edit.inventory_save, name="inventory-edit-save"),
    url(r'^konfigurasi/(?P<konfigurasi_id>[0-9]+)/edit/$', views.edit.konfigurasi, name="konfigurasi-edit"),
    url(r'^konfigurasi/(?P<konfigurasi_id>[0-9]+)/edit/save$', views.edit.konfigurasi_save, name="konfigurasi-edit-save"),
    # url(r'^gaji/(?P<gaji_id>[0-9]+)/edit/$', views.edit.gaji, name="gaji-edit"),
    # url(r'^gaji/(?P<gaji_id>[0-9]+)/edit/save$', views.edit.gaji_save, name="gaji-edit-save"),
    url(r'^karyawan/(?P<karyawan_id>[0-9]+)/edit/$', views.edit.karyawan, name="karyawan-edit"),
    url(r'^karyawan/(?P<karyawan_id>[0-9]+)/edit/save$', views.edit.karyawan_save, name="karyawan-edit-save"),
    url(r'^masatenggangclosing/(?P<masatenggangclosing_id>[0-9]+)/edit/$', views.edit.masatenggangclosing, name="masatenggangclosing-edit"),
    url(r'^masatenggangclosing/(?P<masatenggangclosing_id>[0-9]+)/edit/save$', views.edit.masatenggangclosing_save, name="masatenggangclosing-edit-save"),
    url(r'^hariraya/(?P<hariraya_id>[0-9]+)/edit/$', views.edit.hariraya, name="hariraya-edit"),
    url(r'^hariraya/(?P<hariraya_id>[0-9]+)/edit/save$', views.edit.hariraya_save, name="hariraya-edit-save"),

    url(r'^tunjangan/(?P<tunjangan_id>[0-9]+)/edit/$', views.edit.tunjangan, name="tunjangan-edit"),
    url(r'^tunjangan/(?P<tunjangan_id>[0-9]+)/edit/save$', views.edit.tunjangan_save, name="tunjangan-edit-save"),
    url(r'^potongan/(?P<potongan_id>[0-9]+)/edit/$', views.edit.potongan, name="potongan-edit"),
    url(r'^potongan/(?P<potongan_id>[0-9]+)/edit/save$', views.edit.potongan_save, name="potongan-edit-save"),
    url(r'^karyawanshift/(?P<karyawanshift_id>[0-9]+)/edit/$', views.edit.karyawanshift, name="karyawanshift-edit"),
    url(r'^karyawanshift/(?P<karyawanshift_id>[0-9]+)/edit/save$', views.edit.karyawanshift_save, name="karyawanshift-edit-save"),
    url(r'^bonusthr/(?P<bonusthr_id>[0-9]+)/edit/$', views.edit.bonusthr, name="bonusthr-edit"),
    url(r'^bonusthr/(?P<bonusthr_id>[0-9]+)/edit/save$', views.edit.bonusthr_save, name="bonusthr-edit-save"),
    url(r'^bonusthr/(?P<bonusthr_id>[0-9]+)/off$', views.edit.bonusthr_toggle_off, name="bonusthr-toggle-off"),
    url(r'^bonusthr/(?P<bonusthr_id>[0-9]+)/on$', views.edit.bonusthr_toggle_on, name="bonusthr-toggle-on"),

    url(r'^mesin/(?P<mesin_id>[0-9]+)/edit/$', views.edit.mesin, name="mesin-edit"),
    url(r'^mesin/(?P<mesin_id>[0-9]+)/edit/save$', views.edit.mesin_save, name="mesin-edit-save"),

    #==eofedit

    url(r'^perusahaan/(?P<perusahaan_id>[0-9]+)/delete/$', views.delete.perusahaan, name="perusahaan-delete"),
    url(r'^departemen/(?P<departemen_id>[0-9]+)/delete/$', views.delete.departemen, name="departemen-delete"),
    url(r'^bagian/(?P<bagian_id>[0-9]+)/delete/$', views.delete.bagian, name="bagian-delete"),
    url(r'^golongan/(?P<golongan_id>[0-9]+)/delete/$', views.delete.golongan, name="golongan-delete"),
    url(r'^jabatan/(?P<jabatan_id>[0-9]+)/delete/$', views.delete.jabatan, name="jabatan-delete"),
    url(r'^bank/(?P<bank_id>[0-9]+)/delete/$', views.delete.bank, name="bank-delete"),
    url(r'^agama/(?P<agama_id>[0-9]+)/delete/$', views.delete.agama, name="agama-delete"),
    url(r'^warganegara/(?P<warganegara_id>[0-9]+)/delete/$', views.delete.warganegara, name="warganegara-delete"),
    url(r'^statusmenikah/(?P<statusmenikah_id>[0-9]+)/delete/$', views.delete.statusmenikah, name="statusmenikah-delete"),
    url(r'^profile-perusahaan/(?P<lokasiperusahaan_id>[0-9]+)/delete/$', views.delete.profile_perusahaan, name="profile-perusahaan-delete"),
    url(r'^shift/(?P<shift_id>[0-9]+)/delete/$', views.delete.shift, name="shift-delete"),

    url(r'^hariraya/(?P<hariraya_id>[0-9]+)/delete/$', views.delete.hariraya, name="hariraya-delete"),
    url(r'^inventory/(?P<inventory_id>[0-9]+)/delete/$', views.delete.inventory, name="inventory-delete"),
    # url(r'^gaji/(?P<gajia_id>[0-9]+)/delete/$', views.delete.gaji, name="gaji-delete"),
    url(r'^karyawan/(?P<karyawan_id>[0-9]+)/delete/$', views.delete.karyawan, name="karyawan-delete"),
    url(r'^masatenggangclosing/(?P<masatenggangclosing_id>[0-9]+)/delete/$', views.delete.masatenggangclosing, name="masatenggangclosing-delete"),
    url(r'^tunjangan/(?P<tunjangan_id>[0-9]+)/delete/$', views.delete.tunjangan, name="tunjangan-delete"),
    url(r'^potongan/(?P<potongan_id>[0-9]+)/delete/$', views.delete.potongan, name="potongan-delete"),
    url(r'^karyawanshift/(?P<karyawanshift_id>[0-9]+)/delete/$', views.delete.karyawanshift, name="karyawanshift-delete"),
    url(r'^bpjs/(?P<bpjs_id>[0-9]+)/delete/$', views.delete.bpjs, name="bpjs-delete"),
    url(r'^bonusthr/(?P<bonusthr_id>[0-9]+)/delete/$', views.delete.bonusthr, name="bonusthr-delete"),
    url(r'^konfigurasi/(?P<konfigurasi_id>[0-9]+)/delete/$', views.dashboard.konfigurasi_del, name="konfigurasi-delete"),
    url(r'^mesin/(?P<mesin_id>[0-9]+)/delete/$', views.delete.mesin, name="mesin-delete"),
    #===api

    url(r'^api/karyawan$', views.dashboard.api_karyawan, name="karyawan-api"),
    url(r'^karyawan-shift/edit/save$', views.edit.karyawan_shift, name="karyawan-shift-simpan-api"),
    url(r'^api/karyawan/create/save$', views.create.karyawan_save_api, name="karyawan-create-save-api"),
    url(r'^api/karyawan/lembur/create/save$', views.create.karyawan_lembur_save_api, name="karyawan-lembur-create-save-api"),
    url(r'^api/karyawan/izin/create/save$', views.create.karyawan_izin_save_api, name="karyawan-izin-create-save-api"),
    url(r'^api/potongan/save$', views.create.potongan_save, name="potongan-save"),
    url(r'^api/tunjangan/save$', views.create.tunjangan_save, name="tunjangan-save"),
    url(r'^api/bpjs/save$', views.create.bpjs_save, name="bpjs-save"),
    url(r'^api/bonus/save$', views.create.bonus_save, name="bonus-save"),
    url(r'^api/machine/check$', views.cek_mesin,  name="machine-check"),
]

handler404  = 'system.views.pindahinkalo404' 