from views import *
from dashboard import *
from create import *
from edit import *
from delete import *
from search import *
from posting import *
from laporan import *
from datakaryawan import *
from testing import *